spring.application.name=sonar-demo-springboot

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
# Security hotspot: credentials stored in plaintext config
spring.datasource.password=s3cr3tP@ssw0rd

spring.sql.init.mode=always
